name: Documentation
description: Report missing, unclear, or incorrect documentation.
title: "[Docs]: "
labels:
  - "type: documentation"
  - "area: docs"
body:
  - type: textarea
    id: location
    attributes:
      label: Documentation location
    validations:
      required: true
  - type: textarea
    id: issue
    attributes:
      label: What needs to change?
    validations:
      required: true
  - type: textarea
    id: suggested
    attributes:
      label: Suggested update
